[ 	{ "type" : "sphere", "texture" : "Ball1.jpg", "x" : "0", "y" : "0" },
 	{ "type" : "sphere", "texture" : "Ball2.jpg", "x" : "3", "y" : "0" },
 	{ "type" : "sphere", "texture" : "Ball3.jpg", "x" : "6", "y" : "0" },
 	{ "type" : "sphere", "texture" : "Ball4.jpg", "x" : "9", "y" : "0" },
 	{ "type" : "sphere", "texture" : "Ball5.jpg", "x" : "12", "y" : "0" },
 	{ "type" : "sphere", "texture" : "Ball6.jpg", "x" : "15", "y" : "0" },
 	{ "type" : "sphere", "texture" : "Ball7.jpg", "x" : "18", "y" : "0" },
 	{ "type" : "sphere", "texture" : "Ball8.jpg", "x" : "21", "y" : "0" },
 	{ "type" : "sphere", "texture" : "Ball9.jpg", "x" : "24", "y" : "0" },
 	{ "type" : "sphere", "texture" : "Ball10.jpg", "x" : "27", "y" : "0" },
 	{ "type" : "sphere", "texture" : "Ball11.jpg", "x" : "30", "y" : "0" },
 	{ "type" : "sphere", "texture" : "Ball12.jpg", "x" : "33", "y" : "0" },
 	{ "type" : "sphere", "texture" : "Ball13.jpg", "x" : "36", "y" : "0" },
 	{ "type" : "sphere", "texture" : "Ball14.jpg", "x" : "39", "y" : "0" },
 	{ "type" : "sphere", "texture" : "Ball15.jpg", "x" : "42", "y" : "0" }]