[ 	{ "type" : "sphere", "texture" : "Ball1.jpg", "ball" : "solid"},
 	{ "type" : "sphere", "texture" : "Ball2.jpg", "ball" : "solid"},
 	{ "type" : "sphere", "texture" : "Ball3.jpg", "ball" : "solid"},
 	{ "type" : "sphere", "texture" : "Ball4.jpg", "ball" : "solid"},
 	{ "type" : "sphere", "texture" : "Ball5.jpg", "ball" : "solid"},
 	{ "type" : "sphere", "texture" : "Ball6.jpg", "ball" : "solid"},
 	{ "type" : "sphere", "texture" : "Ball7.jpg", "ball" : "solid"},
 	{ "type" : "sphere", "texture" : "Ball8.jpg", "ball" : "8ball"},
 	{ "type" : "sphere", "texture" : "Ball9.jpg", "ball" : "stripe"},
 	{ "type" : "sphere", "texture" : "Ball10.jpg", "ball" : "stripe"},
 	{ "type" : "sphere", "texture" : "Ball11.jpg", "ball" : "stripe"},
 	{ "type" : "sphere", "texture" : "Ball12.jpg", "ball" : "stripe"},
 	{ "type" : "sphere", "texture" : "Ball13.jpg", "ball" : "stripe"},
 	{ "type" : "sphere", "texture" : "Ball14.jpg", "ball" : "stripe"},
 	{ "type" : "sphere", "texture" : "Ball15.jpg", "ball" : "stripe"},
 	{ "type" : "sphere", "texture" : "BallCue.jpg", "ball" : "cue"}]
